export const characters = [
    // UR: Ultra Rare (Power 8000-9999) - 5 characters
    { name: 'Monkey D. Luffy (Gear 5)', power: 9999, rarity: 'UR' },
    { name: 'Satoru Gojo', power: 9800, rarity: 'UR' },
    { name: 'Saitama', power: 9999, rarity: 'UR' },
    { name: 'Ryomen Sukuna', power: 9700, rarity: 'UR' },
    { name: 'Naruto Uzumaki (Baryon Mode)', power: 9600, rarity: 'UR' },

    // SR: Super Rare (Power 5000-7999) - 10 characters
    { name: 'Roronoa Zoro (King of Hell)', power: 7800, rarity: 'SR' },
    { name: 'Uchiha Sasuke (Rinnegan)', power: 7700, rarity: 'SR' },
    { name: 'Yuta Okkotsu', power: 7500, rarity: 'SR' },
    { name: 'Eren Yeager (Founding Titan)', power: 7900, rarity: 'SR' },
    { name: 'Levi Ackerman', power: 7400, rarity: 'SR' },
    { name: 'Tanjiro Kamado (Hinokami)', power: 7200, rarity: 'SR' },
    { name: 'Ichigo Kurosaki (Bankai)', power: 7600, rarity: 'SR' },
    { name: 'Son Goku (Ultra Instinct)', power: 7950, rarity: 'SR' },
    { name: 'Gon Freecss (Adult)', power: 7850, rarity: 'SR' },
    { name: 'Killua Zoldyck (Godspeed)', power: 7300, rarity: 'SR' },

    // R: Rare (Power 2000-4999) - 15 characters
    { name: 'Sanji (Ifrit Jambe)', power: 4900, rarity: 'R' },
    { name: 'Zenitsu Agatsuma', power: 4200, rarity: 'R' },
    { name: 'Inosuke Hashibira', power: 3800, rarity: 'R' },
    { name: 'Nezuko Kamado', power: 4100, rarity: 'R' },
    { name: 'Megumi Fushiguro', power: 4500, rarity: 'R' },
    { name: 'Toguro (100%)', power: 4800, rarity: 'R' },
    { name: 'Mikasa Ackerman', power: 3900, rarity: 'R' },
    { name: 'Bakugo Katsuki', power: 4600, rarity: 'R' },
    { name: 'Shoto Todoroki', power: 4700, rarity: 'R' },
    { name: 'Izuku Midoriya', power: 4750, rarity: 'R' },
    { name: 'Gaara', power: 4400, rarity: 'R' },
    { name: 'Rock Lee', power: 4300, rarity: 'R' },
    { name: 'Kakashi Hatake (Sharingan)', power: 4950, rarity: 'R' },
    { name: 'Erwin Smith', power: 2500, rarity: 'R' },
    { name: 'Trafalgar Law', power: 4850, rarity: 'R' },

    // C: Common (Power 100-1999) - 20 characters
    { name: 'Sakura Haruno', power: 1800, rarity: 'C' },
    { name: 'Usopp', power: 1200, rarity: 'C' },
    { name: 'Nami', power: 1100, rarity: 'C' },
    { name: 'Tony Tony Chopper', power: 1500, rarity: 'C' },
    { name: 'Konohamaru', power: 900, rarity: 'C' },
    { name: 'Iruka Sensei', power: 600, rarity: 'C' },
    { name: 'Mumen Rider', power: 200, rarity: 'C' },
    { name: 'Genos', power: 1950, rarity: 'C' },
    { name: 'Connie Springer', power: 800, rarity: 'C' },
    { name: 'Sasha Braus', power: 850, rarity: 'C' },
    { name: 'Jean Kirstein', power: 1300, rarity: 'C' },
    { name: 'Historia Reiss', power: 400, rarity: 'C' },
    { name: 'Panda', power: 1700, rarity: 'C' },
    { name: 'Toge Inumaki', power: 1600, rarity: 'C' },
    { name: 'Maki Zenin', power: 1850, rarity: 'C' },
    { name: 'Tenten', power: 1150, rarity: 'C' },
    { name: 'Kiba Inuzuka', power: 1400, rarity: 'C' },
    { name: 'Shino Aburame', power: 1550, rarity: 'C' },
    { name: 'Hinata Hyuga', power: 1750, rarity: 'C' },
    { name: 'Reiner Braun', power: 1900, rarity: 'C' }
];
